%main
clear;
close all;
clc;
ref=imread('../../lena.bmp');
%figure(1)
%imshow(ref);
img1=ref-20;
%figure(2)
%imshow(img1);
psnr1=cal_psnr(ref,img1);
ssim1=ssim(ref,img1);
cal_ssim1=cal_ssim(ref,img1)
img2=double(ref)+(normrnd(0,20,size(ref)));
img2=uint8(img2);
%figure(3)
%imshow(img2);
psnr2=cal_psnr(ref,img2);
ssim2=ssim(ref,img2);
cal_ssim2=cal_ssim(ref,img2)
img3=imresize(ref,[33,33]);
img3=imresize(img3,[512,512]);
%figure(4)
%imshow(img3);
psnr3=cal_psnr(ref,img3);
ssim3=ssim(ref,img3);
cal_ssim3=cal_ssim(ref,img3)
figure(1)
subplot(1,4,1)
imshow(ref)
title('原图');
subplot(1,4,2)
imshow(img1)
title('灰度值减小');
subplot(1,4,3)
imshow(img2)
title('加上高斯噪声');
subplot(1,4,4)
imshow(img3)
title('下采样后上采样');

